name: os
description: Hikari's personal operating system.

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 41

modules:
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks

  - type: signing
