# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: os
description: OS

base-image: quay.io/fedora/fedora-silverblue
image-version: 42

modules:
  - type: signing@v1

  - type: dnf@v1
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/packages/refs/heads/f%OS_VERSION%/anda/terra/release/terra.repo
      copr:
        - latin-1/os-packages
        - peterwu/iosevka
    install:
      packages:
        - adobe-source-han-sans-fonts
        - adobe-source-han-serif-fonts
        - adobe-source-sans-pro-fonts
        - adobe-source-serif-pro-fonts
        - android-udev-rules
        - google-noto-fonts-all
        - gstreamer1-plugin-openh264
        - ibus-rime
        - iosevka-fonts
        - iosevka-term-fonts
        - openh264
        - steam-devices
    remove:
      packages:
        - firefox
        - gnome-system-monitor

  - type: dnf@v1
    install:
      packages:
        - android-tools
        - bat
        - clang
        - eza
        - fastfetch
        - fd-find
        - fish
        - git-delta
        - llvm
        - neovim
        - python3-ramalama
        - ripgrep
        - scrcpy
        - starship
        - typst
        - unar
        - wimlib-utils
        - yadm
        - zed-preview
    group-install:
      packages:
        - development-tools

  - type: script@v1
    snippets:
      - rm -rf /etc/skel && mkdir /etc/skel

  - type: files@v1
    files:
      - source: system
        destination: /

  - type: gschema-overrides

  - type: bling@v1
    install:
      - dconf-update-service

  - type: default-flatpaks@v2
    configurations:
      - scope: system
        install:
          - com.discordapp.Discord
          - com.google.Chrome
          - com.spotify.Client
          - com.usebottles.bottles
          - com.valvesoftware.Steam
          - net.davidotek.pupgui2
          - net.nokyan.Resources
          - org.gnome.Calculator
          - org.gnome.Characters
          - org.gnome.Extensions
          - org.gnome.Loupe
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers
          - org.gnome.Showtime
          - org.gnome.Snapshot
          - org.gnome.TextEditor
        notify: false
      - scope: system
        repo:
          name: flathub-beta
          title: Flathub Beta
          url: https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo
        install:
          - com.valvesoftware.Steam
        notify: false
