# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: os
description: Hikari's personal operating system.

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 41

modules:
  - type: signing

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/latin-1/os-packages/repo/fedora-%OS_VERSION%/latin-1-os-packages-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/iosevka/repo/fedora-%OS_VERSION%/peterwu-iosevka-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/shells:fish:release:4/Fedora_%OS_VERSION%/shells:fish:release:4.repo
      - https://raw.githubusercontent.com/terrapkg/packages/refs/heads/f%OS_VERSION%/anda/terra/release/terra.repo
    install:
      - adobe-source-han-sans-fonts
      - adobe-source-han-serif-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - android-tools
      - android-udev-rules
      - fish
      - google-noto-fonts-all
      - gstreamer1-plugin-openh264
      - ibus-rime
      - iosevka-fonts
      - iosevka-term-fonts
      - neovim
      - openh264
      - steam-devices
    remove:
      - firefox
      - firefox-langpacks
      - noopenh264

  - type: rpm-ostree
    install:
      - fastfetch
      - unar
      - wimlib-utils
      - zed-preview

  - type: script
    snippets:
      - rm -rf /etc/skel && mkdir /etc/skel

  - type: files
    files:
      - source: system
        destination: /

  - type: gschema-overrides

  - type: systemd
    user:
      enabled:
        - gpg-agent.socket

  - type: bling
    install:
      - dconf-update-service

  - type: default-flatpaks
    system:
      install:
        - com.google.Chrome
        - com.usebottles.bottles
        - net.nokyan.Resources
        - org.gnome.Calculator
        - org.gnome.Characters
        - org.gnome.Extensions
        - org.gnome.Loupe
        - org.gnome.NautilusPreviewer
        - org.gnome.Papers
        - org.gnome.Showtime
        - org.gnome.Snapshot
        - org.gnome.TextEditor
