# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: os
description: OS

base-image: quay.io/fedora/fedora-silverblue
image-version: 42

modules:
  - type: signing

  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/packages/refs/heads/f%OS_VERSION%/anda/terra/release/terra.repo
      copr:
        - latin-1/os-packages
        - peterwu/iosevka
    install:
      packages:
        - adobe-source-han-sans-fonts
        - adobe-source-han-serif-fonts
        - adobe-source-sans-pro-fonts
        - adobe-source-serif-pro-fonts
        - google-noto-fonts-all
        - gstreamer1-plugin-openh264
        - ibus-rime
        - iosevka-fonts
        - iosevka-term-fonts
        - openh264
        - steam-devices
    remove:
      packages:
        - firefox

  - type: dnf
    install:
      packages:
        - android-tools
        - android-udev-rules
        - bat
        - eza
        - fastfetch
        - fd-find
        - fish
        - git-delta
        - neovim
        - ripgrep
        - starship
        - typst
        - unar
        - wimlib-utils
        - yadm
        - zed-preview
    group-install:
      packages:
        - development-tools

  - type: script
    snippets:
      - rm -rf /etc/skel && mkdir /etc/skel

  - type: files
    files:
      - source: system
        destination: /

  - type: gschema-overrides

  - type: systemd
    user:
      enabled:
        - gpg-agent.socket

  - type: bling
    install:
      - dconf-update-service

  - type: default-flatpaks
    system:
      install:
        - com.google.Chrome
        - com.usebottles.bottles
        - net.nokyan.Resources
        - org.gnome.Calculator
        - org.gnome.Characters
        - org.gnome.Extensions
        - org.gnome.Loupe
        - org.gnome.NautilusPreviewer
        - org.gnome.Papers
        - org.gnome.Showtime
        - org.gnome.Snapshot
        - org.gnome.TextEditor
